services:
  - type: web
    name: presidente-de-rua-api
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: cd src && gunicorn core.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.13.5"
