# Generated by Django 6.0.4 on 2026-05-12 00:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('distribuicao', 'Problemas com distribuição'), ('atendimento', 'Atendimento inadequado'), ('cadastro', 'Dificuldades no cadastro'), ('outro', 'Outro assunto')], default='distribuicao', max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('reviewed', 'Em análise'), ('resolved', 'Resolvida')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'denúncia anônima',
                'verbose_name_plural': 'denúncias anônimas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_responsavel', models.CharField(max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('codigo_viela', models.CharField(max_length=120)),
                ('complemento', models.CharField(blank=True, max_length=120)),
                ('bairro', models.CharField(blank=True, max_length=120)),
                ('cep', models.CharField(blank=True, max_length=12)),
                ('cidade', models.CharField(default='São Paulo', max_length=120)),
                ('estado', models.CharField(default='SP', max_length=2)),
                ('quantidade_moradores', models.PositiveIntegerField()),
                ('observacoes', models.TextField(blank=True)),
                ('data_ultimo_recebimento', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'família',
                'verbose_name_plural': 'famílias',
                'ordering': ['nome_responsavel'],
                'constraints': [models.UniqueConstraint(fields=('nome_responsavel', 'codigo_viela'), name='unique_family_by_responsible_and_alley')],
            },
        ),
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(default=django.utils.timezone.localdate)),
                ('items', models.CharField(default='Cesta básica padrão', help_text='Itens ou descrição resumida da entrega.', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_logs', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='families.family')),
            ],
            options={
                'verbose_name': 'entrega',
                'verbose_name_plural': 'entregas',
                'ordering': ['-delivery_date', '-created_at'],
            },
        ),
    ]
