# Generated by Django 6.0.4 on 2026-05-12 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.RemoveField(
            model_name='family',
            name='data_ultimo_recebimento',
        ),
        migrations.DeleteModel(
            name='DeliveryLog',
        ),
    ]
