# Generated by Django 6.0.4 on 2026-05-13 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0002_delete_complaint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='families.family')),
            ],
            options={
                'verbose_name': 'entrega',
                'verbose_name_plural': 'entregas',
                'ordering': ['-delivery_date', '-created_at'],
            },
        ),
    ]
