# Generated by Django 6.0.4 on 2026-05-25 18:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0003_deliverylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverylog',
            name='delivery_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
