# Generated by Django 6.0.4 on 2026-06-02 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0004_alter_deliverylog_delivery_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo_area', models.CharField(blank=True, max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Presidente de Rua',
                'verbose_name_plural': 'Presidentes de Rua',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='deliverylog',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='families.fieldagent'),
        ),
        migrations.AddField(
            model_name='family',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_families', to='families.fieldagent'),
        ),
    ]
