# Generated by Django 6.0.4 on 2026-06-03 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0005_fieldagent_deliverylog_agent_family_assigned_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'região',
                'verbose_name_plural': 'regiões',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='family',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families', to='families.region'),
        ),
    ]
