# Generated by Django 6.0.4 on 2026-06-05 14:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0006_region_family_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketAvailabilityNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp')], default='whatsapp', max_length=20)),
                ('status', models.CharField(choices=[('ready', 'Pronta para envio'), ('no_contact', 'Sem contato')], default='ready', max_length=20)),
                ('scheduled_for', models.DateTimeField()),
                ('pickup_location', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('contact_value', models.CharField(blank=True, max_length=40)),
                ('notification_url', models.URLField(blank=True)),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_notifications', to='families.family')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availability_notifications', to='families.region')),
            ],
            options={
                'verbose_name': 'notificação de disponibilidade',
                'verbose_name_plural': 'notificações de disponibilidade',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('family', 'scheduled_for', 'pickup_location'), name='unique_basket_availability_notification')],
            },
        ),
    ]
