# Generated by Django 6.0.4 on 2026-06-05 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0007_basketavailabilitynotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(editable=False, max_length=32, unique=True)),
                ('codigo_viela', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(choices=[('irregular_distribution', 'Irregularidade na distribuição'), ('conflict', 'Conflito em campo'), ('data_issue', 'Dados incorretos'), ('other', 'Outro')], default='other', max_length=40)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('new', 'Nova'), ('in_review', 'Em análise'), ('resolved', 'Resolvida')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anonymous_complaints', to='families.region')),
            ],
            options={
                'verbose_name': 'denúncia anônima',
                'verbose_name_plural': 'denúncias anônimas',
                'ordering': ['-created_at'],
            },
        ),
    ]
