# Generated by Django 6.0.4 on 2026-06-05 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0008_anonymouscomplaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldagent',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_agents', to='families.region'),
        ),
        migrations.AddField(
            model_name='fieldagent',
            name='telefone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
